version: '3.3'

services:
  explorer:
    image: consensys/quorum-explorer:latest
    volumes:
      - ./config.json:/app/config.json
      - ./.env.production:/app/.env.production
    ports:
      - 25000:25000/tcp
    networks:
      - postnet

  node0:
    build:
      context: .
      dockerfile: buildnode.Dockerfile
      args:
        - NODE=validator0
    restart: unless-stopped
    hostname: node0
    env_file:
      - .env
    command:
      --datadir ./data
      --identity node0
      --networkid ${NETWORK_ID} --nodiscover
      --syncmode full
      --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints
      --unlock ${ADDRESS_VALIDATOR_0} --allow-insecure-unlock --password ./data/keystore/accountPassword
      --http --http.addr 0.0.0.0 --http.port 22000 --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr 0.0.0.0 --ws.port 32000 --ws.origins "*"
      --http.api admin,eth,debug,miner,net,txpool,personal,web3
      --ws.api admin,eth,debug,miner,net,txpool,personal,web3
      --port 30300 
    ports:
      - "30300:30300"
      - "22000:22000"
      - "32000:32000"
    networks:
      - postnet

  node1:
    build:
      context: .
      dockerfile: buildnode.Dockerfile
      args:
        - NODE=validator1
    restart: unless-stopped
    hostname: node1
    env_file:
      - .env
    command:
      --datadir ./data
      --identity node1
      --networkid ${NETWORK_ID} --nodiscover
      --syncmode full
      --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints
      --unlock ${ADDRESS_VALIDATOR_1} --allow-insecure-unlock --password ./data/keystore/accountPassword
      --http --http.addr 0.0.0.0 --http.port 22001 --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr 0.0.0.0 --ws.port 32001 --ws.origins "*"
      --http.api admin,eth,debug,miner,net,txpool,personal,web3
      --ws.api admin,eth,debug,miner,net,txpool,personal,web3
      --port 30301 
    ports:
      - "30301:30301"
      - "22001:22001"
      - "32001:32001"
    networks:
      - postnet

  node2:
    build:
      context: .
      dockerfile: buildnode.Dockerfile
      args:
        - NODE=validator2
    restart: unless-stopped
    hostname: node2
    env_file:
      - .env
    command:
      --datadir ./data
      --identity node2
      --networkid ${NETWORK_ID} --nodiscover
      --syncmode full
      --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints
      --unlock ${ADDRESS_VALIDATOR_2} --allow-insecure-unlock --password ./data/keystore/accountPassword
      --http --http.addr 0.0.0.0 --http.port 22002 --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr 0.0.0.0 --ws.port 32002 --ws.origins "*"
      --http.api admin,eth,debug,miner,net,txpool,personal,web3
      --ws.api admin,eth,debug,miner,net,txpool,personal,web3
      --port 30302 
    ports:
      - "30302:30302"
      - "22002:22002"
      - "32002:32002"
    networks:
      - postnet


  node3:
    build:
      context: .
      dockerfile: buildnode.Dockerfile
      args:
        - NODE=validator3
    restart: unless-stopped
    hostname: node3
    env_file:
      - .env
    command:
      --datadir ./data
      --identity node3
      --networkid ${NETWORK_ID} --nodiscover
      --syncmode full
      --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints
      --unlock ${ADDRESS_VALIDATOR_3} --allow-insecure-unlock --password ./data/keystore/accountPassword
      --http --http.addr 0.0.0.0 --http.port 22003 --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr 0.0.0.0 --ws.port 32003 --ws.origins "*"
      --http.api admin,eth,debug,miner,net,txpool,personal,web3
      --ws.api admin,eth,debug,miner,net,txpool,personal,web3
      --port 30303
    ports:
      - "30303:30303"
      - "22003:22003"
      - "32003:32003"
    networks:
      - postnet

  node4:
    build:
      context: .
      dockerfile: buildnode.Dockerfile
      args:
        - NODE=validator4
    restart: unless-stopped
    hostname: node4
    env_file:
      - .env
    command:
      --datadir ./data
      --identity node4
      --networkid ${NETWORK_ID} --nodiscover
      --syncmode full
      --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints
      --unlock ${ADDRESS_VALIDATOR_4} --allow-insecure-unlock --password ./data/keystore/accountPassword
      --http --http.addr 0.0.0.0 --http.port 22004 --http.corsdomain "*" --http.vhosts "*"
      --ws --ws.addr 0.0.0.0 --ws.port 32004 --ws.origins "*"
      --http.api admin,eth,debug,miner,net,txpool,personal,web3
      --ws.api admin,eth,debug,miner,net,txpool,personal,web3
      --port 30304
    ports:
      - "30304:30304"
      - "22004:22004"
      - "32004:32004"
    networks:
      - postnet

networks:
  postnet: